'use client'

import { useEffect, useMemo, useState, useTransition } from 'react'
import { MessageCircle, Search, Send } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { markConversationRead, sendMessage } from '@/lib/social/chat-actions'

type Conversation = { conversationId: string; userId: string; username: string; displayName: string }
type Message = { id: string; conversation_id: string; sender_id: string; content: string; created_at: string }

export function MessagesClient({ currentUserId, conversations }: { currentUserId: string; conversations: Conversation[] }) {
  const [selected, setSelected] = useState(conversations[0]?.conversationId ?? '')
  const [messages, setMessages] = useState<Message[]>([])
  const [query, setQuery] = useState('')
  const [text, setText] = useState('')
  const [error, setError] = useState('')
  const [pending, startTransition] = useTransition()
  const active = conversations.find((item) => item.conversationId === selected)
  const filtered = useMemo(() => conversations.filter((item) => item.displayName.toLowerCase().includes(query.toLowerCase()) || item.username.toLowerCase().includes(query.toLowerCase())), [conversations, query])
  useEffect(() => { if (!selected) return; const supabase = createClient(); let alive = true; supabase.from('messages').select('id, conversation_id, sender_id, content, created_at').eq('conversation_id', selected).order('created_at', { ascending: true }).then(({ data }) => { if (alive) setMessages(data ?? []) }); markConversationRead(selected); const channel = supabase.channel(`messages:${selected}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `conversation_id=eq.${selected}` }, (payload) => setMessages((current) => current.some((item) => item.id === payload.new.id) ? current : [...current, payload.new as Message])).subscribe(); return () => { alive = false; supabase.removeChannel(channel) } }, [selected])
  function submit(event: React.FormEvent) { event.preventDefault(); if (!text.trim() || pending || !selected) return; const optimistic: Message = { id: `temp-${Date.now()}`, conversation_id: selected, sender_id: currentUserId, content: text.trim(), created_at: new Date().toISOString() }; setMessages((current) => [...current, optimistic]); setText(''); startTransition(async () => { const result = await sendMessage(selected, optimistic.content); if (result.error) { setMessages((current) => current.filter((item) => item.id !== optimistic.id)); setError(result.error) } }) }
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border px-4 py-5"><div className="mx-auto flex max-w-5xl items-center gap-3"><a href="/app" className="font-serif text-2xl">luma</a><span className="text-muted-foreground">/ messages</span></div></header><div className="mx-auto grid max-w-5xl md:grid-cols-[280px_1fr] md:gap-6 md:p-6"><aside className="border-b border-border p-4 md:border md:rounded-2xl"><h1 className="font-serif text-3xl">Messages</h1><label className="mt-4 flex items-center gap-2 rounded-xl border border-border px-3 py-2"><Search className="size-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search" aria-label="Search conversations" className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label><div className="mt-4 flex gap-2 overflow-x-auto md:flex-col">{filtered.map((item) => <button key={item.conversationId} onClick={() => setSelected(item.conversationId)} className={`min-w-max rounded-xl px-3 py-3 text-left ${selected === item.conversationId ? 'bg-muted' : 'hover:bg-muted/60'}`}><span className="block font-medium">{item.displayName}</span><span className="text-sm text-muted-foreground">@{item.username}</span></button>)}</div></aside><section className="flex min-h-[calc(100vh-180px)] flex-col p-4 md:rounded-2xl md:border md:border-border"><div className="border-b border-border pb-4"><p className="font-medium">{active?.displayName ?? 'No conversation selected'}</p><p className="text-sm text-muted-foreground">{active ? `@${active.username}` : 'Start a conversation from a profile.'}</p></div><div className="flex flex-1 flex-col gap-3 overflow-y-auto py-5">{messages.length ? messages.map((message) => <div key={message.id} className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.sender_id === currentUserId ? 'self-end bg-primary text-primary-foreground' : 'self-start bg-muted'}`}>{message.content}</div>) : <div className="m-auto text-center text-muted-foreground"><MessageCircle className="mx-auto size-7" /><p className="mt-2">No messages yet.</p></div>}</div>{error && <p role="alert" className="pb-2 text-sm text-destructive">{error}</p>}<form onSubmit={submit} className="flex items-end gap-2 border-t border-border pt-4"><textarea value={text} onChange={(event) => setText(event.target.value.slice(0, 2000))} maxLength={2000} rows={2} placeholder="Write a message…" aria-label="Message" className="min-w-0 flex-1 resize-none rounded-xl border border-border bg-transparent p-3 text-sm outline-none" disabled={!active} /><button type="submit" disabled={!text.trim() || pending || !active} aria-label="Send message" className="rounded-full bg-primary p-3 text-primary-foreground disabled:opacity-50"><Send className="size-4" /></button></form></section></div></main>
}
