'use client'

import { useEffect, useState, useTransition } from 'react'
import { Bell, CheckCheck } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { markNotificationRead } from '@/lib/social/chat-actions'

type Notification = { id: string; type: string; readAt: string | null; createdAt: string; actor: string; username: string }
function label(type: string, actor: string) { if (type === 'follow') return `${actor} followed you`; if (type === 'like') return `${actor} liked your post`; if (type === 'message') return `${actor} sent you a message`; if (type === 'comment') return `${actor} commented on your post`; return `${actor} interacted with you` }
export function NotificationsClient({ initialNotifications }: { initialNotifications: Notification[] }) {
  const [items, setItems] = useState(initialNotifications); const [pending, startTransition] = useTransition()
  useEffect(() => { const supabase = createClient(); let channel: ReturnType<typeof supabase.channel> | null = null; const sync = () => { if (document.hidden || channel) return; channel = supabase.channel('notifications').on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'notifications' }, (payload) => { setItems((current) => current.some((item) => item.id === payload.new.id) ? current : [{ id: payload.new.id as string, type: payload.new.type as string, readAt: null, createdAt: payload.new.created_at as string, actor: 'Someone', username: '' }, ...current]) }).subscribe() }; const onVisibility = () => { if (!document.hidden) sync(); else if (channel) { supabase.removeChannel(channel); channel = null } }; sync(); document.addEventListener('visibilitychange', onVisibility); return () => { document.removeEventListener('visibilitychange', onVisibility); if (channel) supabase.removeChannel(channel) } }, [])
  function mark(id?: string) { startTransition(async () => { await markNotificationRead(id); setItems((current) => id ? current.map((item) => item.id === id ? { ...item, readAt: new Date().toISOString() } : item) : current.map((item) => ({ ...item, readAt: new Date().toISOString() }))) }) }
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b border-border px-4 py-5"><div className="mx-auto flex max-w-2xl items-center justify-between"><a href="/app" className="font-serif text-2xl">luma</a><a href="/app/messages" className="text-sm text-muted-foreground hover:text-foreground">Messages</a></div></header><section className="mx-auto flex max-w-2xl flex-col gap-5 px-4 py-8"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">Stay in the loop</p><h1 className="font-serif text-4xl">Notifications</h1></div><button onClick={() => mark()} disabled={pending || !items.some((item) => !item.readAt)} className="flex items-center gap-2 rounded-full border border-border px-3 py-2 text-sm hover:bg-muted disabled:opacity-50"><CheckCheck className="size-4" />Mark all read</button></div><div className="flex flex-col gap-2">{items.length ? items.map((item) => <button key={item.id} onClick={() => !item.readAt && mark(item.id)} className={`flex items-center gap-3 rounded-2xl border border-border p-4 text-left ${item.readAt ? 'bg-card' : 'bg-muted'}`}><Bell className="size-5 shrink-0 text-primary" /><span className="flex-1 text-sm">{label(item.type, item.actor)}<span className="mt-1 block text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</span></span>{!item.readAt && <span className="size-2 rounded-full bg-primary" aria-label="Unread" />}</button>) : <div className="rounded-2xl border border-dashed border-border p-10 text-center text-muted-foreground"><Bell className="mx-auto size-7" /><p className="mt-3">You&apos;re all caught up.</p></div>}</div></section></main>
}
