'use client'

import { useState, useTransition } from 'react'
import { ArrowLeft, Bell, Eye, HelpCircle, Lock, Moon, Shield, Trash2, UserRound } from 'lucide-react'
import { updateAvatar, updateAvatarVisibility, updateNotificationPreferences, updatePassword, updateProfile } from '@/lib/social/account-actions'
import { Avatar } from '@/components/avatar'

type Profile = { username: string; display_name: string; bio: string | null; avatar_path?: string | null; avatar_visible?: boolean }
type Preferences = { likes: boolean; follows: boolean; messages: boolean } | null
type Props = { profile: Profile | null; email: string; preferences: Preferences }
const categories = [['profile','Profile','Your public information',UserRound],['account','Account','Email and account details',Shield],['security','Password and security','Keep your account safe',Lock],['notifications','Notifications','Choose what you hear about',Bell],['privacy','Privacy and rules','Control your experience',Eye],['appearance','Appearance','Theme and display',Moon],['help','Help and support','Find answers and contact us',HelpCircle]] as const

export function SettingsClient({ profile, email, preferences }: Props) {
  const [active, setActive] = useState('profile'); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(''); const [deleted, setDeleted] = useState('')
  const run = (fn: (data: FormData) => Promise<{ error?: string }>, form: HTMLFormElement) => startTransition(async () => setMessage((await fn(new FormData(form))).error ?? 'Changes saved.'))
  const title = categories.find(([id]) => id === active)?.[1] ?? 'Settings'
  async function remove(e: React.FormEvent) { e.preventDefault(); if (deleted !== 'DELETE') return setMessage('Type DELETE to confirm account removal.'); const r = await fetch('/api/account', { method: 'DELETE', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ confirm: deleted }) }); if (r.ok) location.href = '/'; else setMessage('We could not delete your account.') }
  return <main className="min-h-screen bg-background px-4 pb-24 text-foreground md:px-8"><div className="mx-auto max-w-5xl py-6"><a href="/app" className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="size-4" />Back to feed</a><header className="mb-6"><p className="text-sm text-muted-foreground">Account center</p><h1 className="mt-1 font-serif text-4xl">Settings</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Manage your account, privacy, notifications, and how you use Luma.</p></header>{message && <p role="status" className="mb-5 rounded-xl bg-muted px-4 py-3 text-sm">{message}</p>}<div className="grid gap-6 md:grid-cols-[260px_1fr]"><nav className="h-fit rounded-2xl border border-border bg-card p-2" aria-label="Settings categories"><p className="px-3 py-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Settings</p>{categories.map(([id, label, description, Icon]) => <button key={id} onClick={() => { setActive(id); setMessage('') }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left ${active === id ? 'bg-muted' : 'hover:bg-muted/60'}`}><Icon className="size-5 text-muted-foreground" /><span><span className="block text-sm font-medium">{label}</span><span className="block text-xs text-muted-foreground">{description}</span></span></button>)}</nav><section><h2 className="mb-4 border-b border-border pb-4 text-2xl font-semibold">{title}</h2>{active === 'profile' && <Profile profile={profile} pending={pending} run={run} />}{active === 'account' && <><Panel title="Contact information" text="Your email is used for account access and important notices."><p className="rounded-xl border border-border px-4 py-3 text-sm">{email}</p></Panel><Danger deleted={deleted} setDeleted={setDeleted} remove={remove} /></>}{active === 'security' && <Security pending={pending} run={run} />}{active === 'notifications' && <Notifications preferences={preferences} pending={pending} run={run} />}{active === 'privacy' && <Privacy profile={profile} pending={pending} run={run} />}{active === 'appearance' && <Panel title="Appearance" text="Luma follows your device preference for light or dark mode."><p className="rounded-xl border border-border px-4 py-3 text-sm">Theme <span className="float-right text-muted-foreground">System default</span></p></Panel>}{active === 'help' && <Panel title="Help and support" text="Need help with your account or community experience?"><p className="text-sm leading-6 text-muted-foreground">Review the community rules or contact the Luma team if something is not working as expected.</p></Panel>}</section></div></div></main>
}
function Panel({ title, text, children }: { title: string; text: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-border bg-card p-5"><h3 className="text-lg font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p><div className="mt-5">{children}</div></div> }
function Submit({ pending, children }: { pending: boolean; children: React.ReactNode }) { return <button disabled={pending} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground disabled:opacity-60">{children}</button> }
function Profile({ profile, pending, run }: { profile: Profile | null; pending: boolean; run: PropsRun }) { return <div className="flex flex-col gap-5"><Panel title="Profile information" text="This information helps people recognize you."><div className="flex items-center gap-4"><Avatar name={profile?.display_name} path={profile?.avatar_path} visible={profile?.avatar_visible !== false} size="lg" /><form onSubmit={e => { e.preventDefault(); run(updateAvatar, e.currentTarget) }} className="flex flex-col gap-2"><label className="text-sm">Profile photo<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block text-sm" /></label><Submit pending={pending}>Upload avatar</Submit></form></div><form onSubmit={e => { e.preventDefault(); run(updateProfile, e.currentTarget) }} className="mt-6 flex flex-col gap-3"><label className="text-sm">Display name<input name="display_name" defaultValue={profile?.display_name ?? ''} required className="mt-1 w-full rounded-xl border border-input bg-background px-3 py-3" /></label><label className="text-sm">Username<input name="username" defaultValue={profile?.username ?? ''} required className="mt-1 w-full rounded-xl border border-input bg-background px-3 py-3" /></label><label className="text-sm">Bio<textarea name="bio" defaultValue={profile?.bio ?? ''} rows={3} className="mt-1 w-full rounded-xl border border-input bg-background px-3 py-3" /></label><Submit pending={pending}>Save profile</Submit></form></Panel></div> }
type PropsRun = (fn: (data: FormData) => Promise<{ error?: string }>, form: HTMLFormElement) => void
function Security({ pending, run }: { pending: boolean; run: PropsRun }) { return <Panel title="Password" text="Use a unique password with at least 8 characters."><form onSubmit={e => { e.preventDefault(); run(updatePassword, e.currentTarget) }} className="flex max-w-md flex-col gap-3"><input name="password" type="password" minLength={8} required placeholder="New password" className="rounded-xl border border-input bg-background px-3 py-3" /><Submit pending={pending}>Update password</Submit></form></Panel> }
function Notifications({ preferences, pending, run }: { preferences: Preferences; pending: boolean; run: PropsRun }) { return <Panel title="Notification preferences" text="Choose which activity appears in your notifications."><form onSubmit={e => { e.preventDefault(); run(updateNotificationPreferences, e.currentTarget) }} className="flex flex-col gap-3">{[['likes','Likes on your posts'],['follows','New followers'],['messages','New messages']].map(([name,label]) => <label key={name} className="flex justify-between rounded-xl border border-border px-4 py-3 text-sm">{label}<input name={name} type="checkbox" defaultChecked={preferences?.[name as keyof NonNullable<Preferences>] ?? true} /></label>)}<Submit pending={pending}>Save notifications</Submit></form></Panel> }
function Privacy({ profile, pending, run }: { profile: Profile | null; pending: boolean; run: PropsRun }) { return <div className="flex flex-col gap-5"><Panel title="Privacy controls" text="You decide how your profile appears to other members."><form onSubmit={e => { e.preventDefault(); run(updateAvatarVisibility, e.currentTarget) }} className="flex items-center justify-between gap-3 text-sm"><span>Show my avatar to other members</span><input name="avatar_visible" type="checkbox" defaultChecked={profile?.avatar_visible !== false} /><Submit pending={pending}>Save</Submit></form></Panel><Panel title="Community rules" text="These rules keep Luma useful and welcoming."><ul className="list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li>Be respectful; do not harass or threaten members.</li><li>Do not share private information without permission.</li><li>Keep posts and messages lawful, relevant, and honest.</li><li>Report content that violates these rules.</li></ul></Panel></div> }
function Danger({ deleted, setDeleted, remove }: { deleted: string; setDeleted: (v: string) => void; remove: (e: React.FormEvent) => void }) { return <div className="mt-5 rounded-2xl border border-destructive/40 bg-card p-5"><div className="flex gap-3"><Trash2 className="size-5 text-destructive" /><div><h3 className="font-semibold">Delete account</h3><p className="mt-1 text-sm text-muted-foreground">This permanently removes your account and content.</p><form onSubmit={remove} className="mt-4 flex gap-2"><input value={deleted} onChange={e => setDeleted(e.target.value)} placeholder="Type DELETE" className="min-w-0 rounded-xl border border-input bg-background px-3 py-2.5 text-sm" /><button className="rounded-xl border border-destructive px-3 py-2 text-sm text-destructive">Delete</button></form></div></div></div> }

